version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # This mounts the entire project directory, including db.sqlite3
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
